### PR TITLE
Admin Users Address Book

### PR DESCRIPTION
**Pull request by kinduff**
#### What's this PR do?
- Adds addresses table for user
- Adds new edit address view and action

### CODE REVIEW

**Comment by autotelik** [comment]
yeah looks great from the screenshots

one question .. can you change the default billing/shipping 

so if we have a long list of addresses probably want to be able to select a new default via the radio buttons .. and maybe need an  update button, or js pop up,  to confirm/cancel that change 

btw I don't have permissions to merge this  .. looks like I don't have full write access

**Comment by kinduff** [comment]
captura de pantalla de 2015-04-30 11 24 31

**Comment by kinduff** [comment]
This look way much better! @autotelik 

captura de pantalla de 2015-04-30 16 07 39

**Comment by kinduff** [comment]
@autotelik @MFRWDesign This is now complete!

**Comment by autotelik** [comment]
looks perfect. can you merge it in, as I cannot, and can't access your kinduff:admin_users_addresses branch either ... would like to fire it up locally

**Pull request merged**
